### PR TITLE
support https endpoints when port 443 is specified

### PR DESCRIPTION
**Pull request by andymerryman**

### CODE REVIEW

**Comment by gr2m** [comment]
Hey sorry for leaving this open for so long. Do you know about a simple way to start a local server via `https://` for testing? I never had a need for it. 

Also `CORS-Proxy` is now using https://github.com/gr2m/hapi-cors-headers, so that'd  be the place to land the fix now

**Comment by pezza3434** [comment]
@gr2m I agree, would be really nice if this package could support https endpoints. Not sure why the protocol should be changed depending on the port though.

**Comment by acmerrym** [comment]
@gr2m I tested by simply pointing it to https-hosted assets in the wild, rather than credentialing my own local server.

@pezza3434 Port 443 is the port that browsers send https traffic to by default, hence the approach of rewriting requests on that port as https:// and removing the explicit reference to :443 in the proxied url. From a practical standpoint, this works for most use-cases (since port 443 should never be a protocol other than https) and should work for all production-deployed endpoints. It doesn't do ad-hoc ports with ad-hoc protocols - I wanted to retain the existing schema of how urls get fed to the proxy in a way that was backwards-compatible.

**Comment by yuryskaletskiy** [comment]
My five cents: It's a good point discuss how to start the server as https (as well how to deal with all the certificates stuff). 

But in the same time accepting the patch can easily provide http=>https request translation which will cover more than 90% development troubles regarding calls of https endpoints. So I vote for this patch.

BTW, if you think there's poor design proposed, you can provide some parameter turning this on :-) unless the proper way to work with https is found.

**Comment by gr2m** [comment]
hey folks, I’m sorry that I’m not on top of this, I’m not using it myself actively right now. But if you 3 agree on a good solution based on current master with tests passing, I’m happy to merge it in & release

**Comment by brandonros** [comment]
Still needed. :(

**Comment by gr2m** [comment]
it’s not going to make itself, and I cannot do it myself, sorry. See https://github.com/gr2m/CORS-Proxy/pull/38#issuecomment-191869028

**Comment by brandonros** [comment]
The perfect repo owner mentality...

For anybody else:

`npm uninstall -g corsproxy`
`npm install -g https://github.com/andymerryman/CORS-Proxy.git`

**Comment by gr2m** [comment]
well thanks :)

**Pull request closed without merging**
